# Generated by Django 4.2.2 on 2023-06-24 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='olusturma_zamani',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='yayim_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
